### ISSUE TITLE
With pressure test, miner sometimes cannot clear tx pool.

### ISSUE THREAD

**Issue by xujingshi** [BOXFoundation/boxd#225] opened 2018-12-05 18:33 UTC
You can see the problem intuitively now on grafana.
I add some logs on n1, n2 and n3. You will find that `u.FindUtxo(txIn.PrevOutPoint)` cannot find any utxos match the txin. So this tx cannot be packed on chain any more.

**Comment by xhliu** [comment] 2018-12-05 18:36
Duplicate of #218

**Closed** 2018-12-05 18:36 UTC
Labels: bug
