### ISSUE TITLE
[ci broken]Failed to processBlockMsg. Err: The block is timeout, Failed to verify miner epoch

### ISSUE THREAD

**Issue by Jerick26** [BOXFoundation/boxd#203] opened 2018-11-27 16:37 UTC
```
INFO[0005] startLocalNodes: [../box start --config=./.devconfig/.box-1.yaml &]  source="integration_tests/util.go:63" tag=integration_tests
INFO[0005] startLocalNodes: [../box start --config=./.devconfig/.box-2.yaml &]  source="integration_tests/util.go:63" tag=integration_tests
INFO[0005] startLocalNodes: [../box start --config=./.devconfig/.box-3.yaml &]  source="integration_tests/util.go:63" tag=integration_tests
INFO[0005] startLocalNodes: [../box start --config=./.devconfig/.box-4.yaml &]  source="integration_tests/util.go:63" tag=integration_tests
INFO[0005] startLocalNodes: [../box start --config=./.devconfig/.box-5.yaml &]  source="integration_tests/util.go:63" tag=integration_tests
INFO[0005] startLocalNodes: [../box start --config=./.devconfig/.box-6.yaml &]  source="integration_tests/util.go:63" tag=integration_tests
INFO[0005] start to gen 3 address for circulation        source="integration_tests/test_token.go:31" tag=integration_tests
INFO[0005] start to create 3 accounts                    source="integration_tests/boxutil.go:283" tag=integration_tests
INFO[0005] start to gen 10 tests address                 source="integration_tests/collection.go:40" tag=integration_tests
INFO[0005] start to create 10 accounts                   source="integration_tests/boxutil.go:283" tag=integration_tests
ERRO[0000] Failed to new stream to 12D3KooWFQ2naj8XZUVyGhFzBTEMrMc6emiCEDKLjaJMsK7p8Cza, addrs={<peer.ID 12*7p8Cza> [/ip4/127.0.0.1/tcp/19199]}, err = dial attempt failed: <peer.ID 12*ByZDpA> --> <peer.ID 12*7p8Cza> dial attempt failed: connection refused  source="p2p/conn.go:87" tag=p2p
ERRO[0001] Failed to new stream to 12D3KooWFQ2naj8XZUVyGhFzBTEMrMc6emiCEDKLjaJMsK7p8Cza, addrs={<peer.ID 12*7p8Cza> [/ip4/127.0.0.1/tcp/19199]}, err = dial backoff  source="p2p/conn.go:87" tag=p2p
ERRO[0004] Failed to new stream to 12D3KooWFQ2naj8XZUVyGhFzBTEMrMc6emiCEDKLjaJMsK7p8Cza, addrs={<peer.ID 12*7p8Cza> [/ip4/127.0.0.1/tcp/19199]}, err = dial backoff  source="p2p/conn.go:87" tag=p2p
WARN[0007] locateHashes error: no peer to sync           source="blocksync/manager.go:229" tag=blocksync
WARN[0008] locateHashes error: no peer to sync           source="blocksync/manager.go:229" tag=blocksync
WARN[0009] locateHashes error: no peer to sync           source="blocksync/manager.go:229" tag=blocksync
INFO[0015] start to unlock all 3 tests accounts          source="integration_tests/test_token.go:35" tag=integration_tests
WARN[0010] locateHashes error: no peer to sync           source="blocksync/manager.go:229" tag=blocksync
WARN[0011] locateHashes error: no peer to sync           source="blocksync/manager.go:229" tag=blocksync
WARN[0012] locateHashes error: no peer to sync           source="blocksync/manager.go:229" tag=blocksync
WARN[0013] locateHashes error: no peer to sync           source="blocksync/manager.go:229" tag=blocksync
INFO[0028] wait for block height of all nodes reach 2, timeout 30s  source="integration_tests/main.go:215" tag=integration_tests
INFO[0029] start TokenTest doTx                          source="integration_tests/test_token.go:62" tag=integration_tests
INFO[0029] waiting for minersAddr has 1000000 at least on 127.0.0.1:19111  source="integration_tests/test_token.go:73" tag=integration_tests
INFO[0035] send 500000 from b1XnieZrZU5PNCdkvCnu9Yks8o6igLxJFSx to b1evsRV7HS97D6qa7g3ZSrCRYK89DsvdehB  source="integration_tests/test_token.go:84" tag=integration_tests
WARN[0030] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
ERRO[0030] Failed to sync route table from peer: 12D3KooWFQ2naj8XZUVyGhFzBTEMrMc6emiCEDKLjaJMsK7p8Cza err: Handshaking timeout  source="p2p/table.go:153" tag=p2p
WARN[0030] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0030] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0030] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0030] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0030] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
INFO[0036] start to unlock all 10 tests accounts         source="integration_tests/collection.go:44" tag=integration_tests
INFO[0036] b1XnieZrZU5PNCdkvCnu9Yks8o6igLxJFSx issue 100000 box token  source="integration_tests/test_token.go:92" tag=integration_tests
INFO[0036] before token transfer, b1evsRV7HS97D6qa7g3ZSrCRYK89DsvdehB has 0 box token  source="integration_tests/test_token.go:97" tag=integration_tests
INFO[0036] b1XnieZrZU5PNCdkvCnu9Yks8o6igLxJFSx transfer 50000 box token to b1evsRV7HS97D6qa7g3ZSrCRYK89DsvdehB  source="integration_tests/test_token.go:99" tag=integration_tests
INFO[0036] wait for token balance of b1evsRV7HS97D6qa7g3ZSrCRYK89DsvdehB reach 50000, timeout 30s  source="integration_tests/test_token.go:104" tag=integration_tests
ERRO[0031] Failed to sync route table from peer: 12D3KooWFQ2naj8XZUVyGhFzBTEMrMc6emiCEDKLjaJMsK7p8Cza err: Handshaking timeout  source="p2p/table.go:153" tag=p2p
ERRO[0034] Failed to sync route table from peer: 12D3KooWFQ2naj8XZUVyGhFzBTEMrMc6emiCEDKLjaJMsK7p8Cza err: Handshaking timeout  source="p2p/table.go:153" tag=p2p
WARN[0035] The block is already exist. Hash: fcb9464fffd1f91efcc4bb756b3f58527ceae0c1c31f9411de6786cdf7c52e9d, Height: 4  source="chain/blockchain.go:236" tag=chain
INFO[0041] b1evsRV7HS97D6qa7g3ZSrCRYK89DsvdehB has 50000 box token  source="integration_tests/test_token.go:108" tag=integration_tests
INFO[0041] done TokenTest doTx                           source="integration_tests/test_token.go:53" tag=integration_tests
INFO[0041] remove 3 keystore files                       source="integration_tests/util.go:207" tag=integration_tests
WARN[0060] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0060] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0060] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0060] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0060] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0060] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0063] Failed to processBlockMsg. Err: The block is timeout  source="chain/blockchain.go:180" tag=chain
WARN[0073] Failed to processBlockMsg. Err: The block is timeout  source="chain/blockchain.go:180" tag=chain
WARN[0076] The block is already exist. Hash: 27ae573c30682add8eb3ad40f075e865dd1fb71519cd0f3e532a7aff78d02d3c, Height: 11  source="chain/blockchain.go:236" tag=chain
INFO[0084] start to gen 10 address for circulation       source="integration_tests/circulation.go:36" tag=integration_tests
INFO[0084] start to create 10 accounts                   source="integration_tests/boxutil.go:283" tag=integration_tests
WARN[0082] The block is already exist. Hash: fc4edd9d0716a7be46a181a73950daa8c5d84c7b3e34609c2d833c59d23bac0a, Height: 12  source="chain/blockchain.go:236" tag=chain
WARN[0090] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0090] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0090] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0090] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0090] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0090] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0093] Failed to processBlockMsg. Err: The block is timeout  source="chain/blockchain.go:180" tag=chain
WARN[0093] Failed to processBlockMsg. Err: The block is timeout  source="chain/blockchain.go:180" tag=chain
WARN[0093] Failed to processBlockMsg. Err: The block is timeout  source="chain/blockchain.go:180" tag=chain
WARN[0093] Failed to processBlockMsg. Err: The block is timeout  source="chain/blockchain.go:180" tag=chain
WARN[0093] Failed to processBlockMsg. Err: The block is timeout  source="chain/blockchain.go:180" tag=chain
INFO[0124] start to unlock all 10 tests accounts         source="integration_tests/circulation.go:40" tag=integration_tests
WARN[0120] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0120] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0120] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0120] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0120] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0120] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0133] Failed to processBlockMsg. Err: The block is timeout  source="chain/blockchain.go:180" tag=chain
WARN[0143] Failed to processBlockMsg. Err: The block is timeout  source="chain/blockchain.go:180" tag=chain
ERRO[0145] Failed to verify miner epoch. Hash: adc24057f64c43f081dbac273570beb331db5a6031f2a4b273c6b47a49956bf2, Height: 23, Err: Invalid miner epoch  source="chain/blockchain.go:319" tag=chain
ERRO[0145] Failed to accept the block into the main chain. Err: Failed to verify block with consensus  source="chain/blockchain.go:268" tag=chain
WARN[0145] Failed to process block. err: Failed to verify block with consensus  source="dpos/dpos.go:228" tag=dpos
WARN[0146] The block is already exist. Hash: fb9a4c964f98b3fa27e385427b8d14df91f7d0ffcffed0017ea9cfe1a61264f5, Height: 23  source="chain/blockchain.go:236" tag=chain
WARN[0150] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0150] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0150] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0150] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0150] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0150] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
ERRO[0150] Failed to verify miner epoch. Hash: e9a28b9849e57db0357db5618a7528a07731653eb4050107c0e37eee17846ee2, Height: 24, Err: Invalid miner epoch  source="chain/blockchain.go:319" tag=chain
ERRO[0150] Failed to accept the block into the main chain. Err: Failed to verify block with consensus  source="chain/blockchain.go:268" tag=chain
WARN[0150] Failed to process block. err: Failed to verify block with consensus  source="dpos/dpos.go:228" tag=dpos
INFO[0156] wait for block height of all nodes reach 2, timeout 30s  source="integration_tests/main.go:188" tag=integration_tests
INFO[0158] start circulation doTx 1                      source="integration_tests/circulation.go:86" tag=integration_tests
INFO[0158] start collection doTx 1                       source="integration_tests/collection.go:91" tag=integration_tests
INFO[0158] waiting for minersAddr has 2000000 at least on 127.0.0.1:19111  source="integration_tests/collection.go:104" tag=integration_tests
INFO[0158] start circulation doTx 0                      source="integration_tests/circulation.go:86" tag=integration_tests
INFO[0158] start collection doTx 0                       source="integration_tests/collection.go:91" tag=integration_tests
INFO[0158] waiting for minersAddr has 2000000 at least on 127.0.0.1:19111  source="integration_tests/collection.go:104" tag=integration_tests
INFO[0158] start to launder some fund 1000000 on 127.0.0.1:19111  source="integration_tests/collection.go:119" tag=integration_tests
INFO[0158] === RUN   launderFunds                        source="integration_tests/collection.go:137" tag=integration_tests
INFO[0158] wait for balance of b1ZgA72CmT7cGpz7L2Jy5JayzpF4WVtumPm more than 120268, timeout 30s  source="integration_tests/collection.go:155" tag=integration_tests
INFO[0158] start to launder some fund 1000000 on 127.0.0.1:19111  source="integration_tests/collection.go:119" tag=integration_tests
INFO[0158] === RUN   launderFunds                        source="integration_tests/collection.go:137" tag=integration_tests
INFO[0158] wait for balance of b1o3MbqkCHK3ZcMCEbtWpdVpE4YT5WEfWdU more than 197086, timeout 30s  source="integration_tests/collection.go:155" tag=integration_tests
ERRO[0155] Failed to verify miner epoch. Hash: 0b6a9aad00b4d3d7194b93d1884014fd0ac6851061f654b3c6b149d2ce643a56, Height: 24, Err: Invalid miner epoch  source="chain/blockchain.go:319" tag=chain
ERRO[0155] Failed to accept the block into the main chain. Err: Failed to verify block with consensus  source="chain/blockchain.go:268" tag=chain
WARN[0155] Failed to process block. err: Failed to verify block with consensus  source="dpos/dpos.go:228" tag=dpos
ERRO[0160] Failed to verify miner epoch. Hash: 7a05cc6b0f025f0772b3dc6c2d7142109bdef1fd89fa6ea96ff5ae54de851e4c, Height: 24, Err: Invalid miner epoch  source="chain/blockchain.go:319" tag=chain
ERRO[0160] Failed to accept the block into the main chain. Err: Failed to verify block with consensus  source="chain/blockchain.go:268" tag=chain
WARN[0160] Failed to process block. err: Failed to verify block with consensus  source="dpos/dpos.go:228" tag=dpos
ERRO[0165] Failed to verify miner epoch. Hash: 28a506646475d7d5ee50cc03b742b0b511165cb9bcef3c20595028d366ca09e4, Height: 24, Err: Invalid miner epoch  source="chain/blockchain.go:319" tag=chain
ERRO[0165] Failed to accept the block into the main chain. Err: Failed to verify block with consensus  source="chain/blockchain.go:268" tag=chain
WARN[0165] Failed to process block. err: Failed to verify block with consensus  source="dpos/dpos.go:228" tag=dpos
ERRO[0170] Failed to verify miner epoch. Hash: d268fd299efd4961031751a791b3b4402e0934819e767c899f23b1df19425020, Height: 24, Err: Invalid miner epoch  source="chain/blockchain.go:319" tag=chain
ERRO[0170] Failed to accept the block into the main chain. Err: Failed to verify block with consensus  source="chain/blockchain.go:268" tag=chain
WARN[0170] Failed to process block. err: Failed to verify block with consensus  source="dpos/dpos.go:228" tag=dpos
ERRO[0175] Failed to verify miner epoch. Hash: 7fcdc4b582affe35a37e49f64149824a06941db6981f1087365b248117d8b274, Height: 23, Err: Invalid miner epoch  source="chain/blockchain.go:319" tag=chain
ERRO[0175] Failed to accept the block into the main chain. Err: Failed to verify block with consensus  source="chain/blockchain.go:268" tag=chain
WARN[0175] Failed to process block. err: Failed to verify block with consensus  source="dpos/dpos.go:228" tag=dpos
WARN[0180] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0180] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0180] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0180] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0180] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
WARN[0180] TrimOpenConns was called, but not implemented.  source="p2p/connmgr.go:266" tag=p2p
ERRO[0180] Failed to verify miner epoch. Hash: 851a0568f9abf6fd14997cdc4df5cd84f76e0619ecdba0c57357ccf596b386da, Height: 24, Err: Invalid miner epoch  source="chain/blockchain.go:319" tag=chain
ERRO[0180] Failed to accept the block into the main chain. Err: Failed to verify block with consensus  source="chain/blockchain.go:268" tag=chain
WARN[0180] Failed to process block. err: Failed to verify block with consensus  source="dpos/dpos.go:228" tag=dpos
PANI[0188] Timeout for waiting for b1ZgA72CmT7cGpz7L2Jy5JayzpF4WVtumPm balance enough 120268, now 0  source="integration_tests/collection.go:160" tag=integration_tests
ERRO[0188] &{0xc0000bc820 map[tag:integration_tests source:integration_tests/collection.go:160] 2018-11-27 15:03:47.92661469 +0000 UTC m=+188.374591862 panic Timeout for waiting for b1ZgA72CmT7cGpz7L2Jy5JayzpF4WVtumPm balance enough 120268, now 0 <nil> }  source="integration_tests/collection.go:133" tag=integration_tests
INFO[0188] start box circulation between accounts on 127.0.0.1:19111  source="integration_tests/circulation.go:101" tag=integration_tests
INFO[0188] === RUN   txRepeatTest                        source="integration_tests/circulation.go:117" tag=integration_tests
WARN[0188] balance of b1cKUDgr3ExixKDdwWw7ybehdUCnrdKn85H is 0, exit  source="integration_tests/circulation.go:125" tag=integration_tests
INFO[0188] done doTx                                     source="integration_tests/circulation.go:74" tag=integration_tests
PANI[0188] Timeout for waiting for b1o3MbqkCHK3ZcMCEbtWpdVpE4YT5WEfWdU balance enough 197086, now 0  source="integration_tests/collection.go:160" tag=integration_tests
ERRO[0188] &{0xc0000bc820 map[tag:integration_tests source:integration_tests/collection.go:160] 2018-11-27 15:03:48.227508162 +0000 UTC m=+188.675485355 panic Timeout for waiting for b1o3MbqkCHK3ZcMCEbtWpdVpE4YT5WEfWdU balance enough 197086, now 0 <nil> }  source="integration_tests/collection.go:133" tag=integration_tests
INFO[0188] done collection                               source="integration_tests/main.go:199" tag=integration_tests
INFO[0188] start box circulation between accounts on 127.0.0.1:19111  source="integration_tests/circulation.go:101" tag=integration_tests
INFO[0188] === RUN   txRepeatTest                        source="integration_tests/circulation.go:117" tag=integration_tests
WARN[0188] balance of b1kqU7qMiDwYsWTahCZaUeugcq6qKBNo5dy is 0, exit  source="integration_tests/circulation.go:125" tag=integration_tests
INFO[0188] done doTx                                     source="integration_tests/circulation.go:74" tag=integration_tests
INFO[0188] done circulation                              source="integration_tests/main.go:206" tag=integration_tests
INFO[0188] remove 10 keystore files                      source="integration_tests/util.go:207" tag=integration_tests
INFO[0188] remove 10 keystore files                      source="integration_tests/util.go:207" tag=integration_tests
ERRO[0188] &{0xc0000bc820 map[tag:integration_tests source:integration_tests/collection.go:160] 2018-11-27 15:03:47.92661469 +0000 UTC m=+188.374591862 panic Timeout for waiting for b1ZgA72CmT7cGpz7L2Jy5JayzpF4WVtumPm balance enough 120268, now 0 <nil> }  source="integration_tests/main.go:162" tag=integration_tests
ERRO[0188] &{0xc0000bc820 map[tag:integration_tests source:integration_tests/collection.go:160] 2018-11-27 15:03:48.227508162 +0000 UTC m=+188.675485355 panic Timeout for waiting for b1o3MbqkCHK3ZcMCEbtWpdVpE4YT5WEfWdU balance enough 197086, now 0 <nil> }  source="integration_tests/main.go:162" tag=integration_tests
PANI[0188] integration tests exits with 2 errors         source="integration_tests/main.go:166" tag=integration_tests
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] failed to update ttlsfor peer 12D3KooWFQ2naj8XZUVyGhFzBTEMrMc6emiCEDKLjaJMsK7p8Cza: database panic  source="pstore/addrbook.go:209" tag=p2p/pstore
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
ERRO[0183] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:108" tag=p2p
INFO[0188] process[19807] exit status 0                  source="integration_tests/util.go:93" tag=integration_tests
INFO[0188] process[19824] exit status 0                  source="integration_tests/util.go:93" tag=integration_tests
INFO[0188] process[19822] exit status 0                  source="integration_tests/util.go:93" tag=integration_tests
INFO[0188] process[19808] exit status 0                  source="integration_tests/util.go:93" tag=integration_tests
INFO[0188] process[19813] exit status 0                  source="integration_tests/util.go:93" tag=integration_tests
INFO[0188] process[19814] exit status 0                  source="integration_tests/util.go:93" tag=integration_tests
The command "./integration_tests -nodes=true" exited with 1.
```

**Comment by xhliu** [comment] 2018-11-27 17:41
Duplicate of #199

**Closed by xhliu** 2018-11-27 17:41 UTC
Labels: bug
